
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check .
        language: system
        types: [python]

      - id: flake8
        name: Flake8
        entry: flake8
        args:
            - "--max-line-length=127"
            - "--max-complexity=10"
            - "--ignore=E501,W605"
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
