name: Lint and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run pre-commit hooks.
      run: SKIP=flake8;
    - name: Lint with flake8
      run: |
        flake8 . --count --ignore=E501 --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
